# Use the official PostgreSQL image as the base image
FROM postgres:16beta2

# Set environment variables for PostgreSQL
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB rubiks_word

# Expose the default PostgreSQL port
EXPOSE 5432